#![allow(unexpected_cfgs)]
pub mod api;

// Generated by flutter_rust_bridge codegen. Kept empty locally so the
// crate builds before running codegen from the Flutter project.
#[allow(clippy::all, unused)]
pub mod bridge_generated;
pub use bridge_generated::*;

// Re-export models used in FRB signatures so they are in-crate for codegen.
pub use rura_models::client_message::{AuthRequest, AuthResponse, ClientMessage};
pub use rura_models::messaging::{HistoryRequest, HistoryResponse};
