// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1419790892;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rura_client',
    ioDirectory: '../target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<CallState> crateApiAcceptCall(
      {required PlatformInt64 userId,
      required String callId,
      required bool enableVideo});

  Future<void> crateApiAddContact(
      {required String userId, required String pubkey});

  Future<void> crateApiAddContactWithNickname(
      {required String userId, required String pubkey, String? nickname});

  Future<void> crateApiAppendLocalMessage(
      {required PlatformInt64 fromUserId,
      required PlatformInt64 toUserId,
      required String body,
      required String timestamp});

  Future<String> crateApiDecryptMessageFromEnvelope({required String envelope});

  Future<String> crateApiEncryptMessageForIdentity(
      {required String toIdentity, required String plaintext});

  Future<void> crateApiEndCall(
      {required PlatformInt64 userId, required String callId});

  Future<String> crateApiGetAccountId();

  Future<String> crateApiGetAccountPubkey();

  Future<CallState?> crateApiGetCurrentCallState();

  Future<String?> crateApiGetPubkeyTls(
      {required String host,
      required int port,
      required String caPem,
      required String passphrase,
      required String password,
      required PlatformInt64 userId});

  Future<String> crateApiListContactsJson();

  Future<List<HistoryMessage>> crateApiLoadLocalHistory({BigInt? limit});

  Future<HistoryBundle> crateApiLoginAndFetchHistoryTls(
      {required String host,
      required int port,
      required String caPem,
      required String passphrase,
      required String password,
      BigInt? limit});

  Future<HistoryBundle> crateApiLoginAndLoadLocalHistoryTls(
      {required String host,
      required int port,
      required String caPem,
      required String passphrase,
      required String password,
      BigInt? limit});

  Future<LoginResponse> crateApiLoginTls(
      {required String host,
      required int port,
      required String caPem,
      required String passphrase,
      required String password});

  Stream<String> crateApiOpenMessageStreamRegisterTls(
      {required String host,
      required int port,
      required String caPem,
      required String passphrase,
      required String password});

  Stream<String> crateApiOpenMessageStreamTls(
      {required String host,
      required int port,
      required String caPem,
      required String passphrase,
      required String password});

  Future<HistoryBundle> crateApiRegisterAndFetchHistoryTls(
      {required String host,
      required int port,
      required String caPem,
      required String passphrase,
      required String password,
      BigInt? limit});

  Future<HistoryBundle> crateApiRegisterAndLoadLocalHistoryTls(
      {required String host,
      required int port,
      required String caPem,
      required String passphrase,
      required String password,
      BigInt? limit});

  Future<LoginResponse> crateApiRegisterTls(
      {required String host,
      required int port,
      required String caPem,
      required String passphrase,
      required String password});

  Future<void> crateApiRejectCall(
      {required PlatformInt64 userId,
      required String callId,
      required bool busy});

  Future<void> crateApiSendDirectMessageOverStream(
      {required PlatformInt64 userId,
      required PlatformInt64 toUserId,
      required String body});

  Future<void> crateApiSendDirectMessageOverStreamToIdentity(
      {required PlatformInt64 userId,
      required String toIdentity,
      required String body});

  Future<SendResult> crateApiSendDirectMessageTls(
      {required String host,
      required int port,
      required String caPem,
      required String passphrase,
      required String password,
      required PlatformInt64 toUserId,
      required String body});

  Future<void> crateApiSendMediaToIdentity(
      {required PlatformInt64 userId,
      required String toIdentity,
      required String mime,
      String? name,
      required List<int> bytes,
      BigInt? chunkSize});

  Future<void> crateApiSetContactNickname(
      {required String userId, String? nickname});

  Future<void> crateApiSetPubkeyOverStream(
      {required PlatformInt64 userId, required String pubkey});

  Future<CallState> crateApiStartCall(
      {required PlatformInt64 userId,
      required PlatformInt64 remoteUserId,
      required bool enableVideo});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<CallState> crateApiAcceptCall(
      {required PlatformInt64 userId,
      required String callId,
      required bool enableVideo}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(userId, serializer);
        sse_encode_String(callId, serializer);
        sse_encode_bool(enableVideo, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_call_state,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAcceptCallConstMeta,
      argValues: [userId, callId, enableVideo],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAcceptCallConstMeta => const TaskConstMeta(
        debugName: "accept_call",
        argNames: ["userId", "callId", "enableVideo"],
      );

  @override
  Future<void> crateApiAddContact(
      {required String userId, required String pubkey}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(userId, serializer);
        sse_encode_String(pubkey, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAddContactConstMeta,
      argValues: [userId, pubkey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAddContactConstMeta => const TaskConstMeta(
        debugName: "add_contact",
        argNames: ["userId", "pubkey"],
      );

  @override
  Future<void> crateApiAddContactWithNickname(
      {required String userId, required String pubkey, String? nickname}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(userId, serializer);
        sse_encode_String(pubkey, serializer);
        sse_encode_opt_String(nickname, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAddContactWithNicknameConstMeta,
      argValues: [userId, pubkey, nickname],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAddContactWithNicknameConstMeta =>
      const TaskConstMeta(
        debugName: "add_contact_with_nickname",
        argNames: ["userId", "pubkey", "nickname"],
      );

  @override
  Future<void> crateApiAppendLocalMessage(
      {required PlatformInt64 fromUserId,
      required PlatformInt64 toUserId,
      required String body,
      required String timestamp}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(fromUserId, serializer);
        sse_encode_i_64(toUserId, serializer);
        sse_encode_String(body, serializer);
        sse_encode_String(timestamp, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAppendLocalMessageConstMeta,
      argValues: [fromUserId, toUserId, body, timestamp],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAppendLocalMessageConstMeta => const TaskConstMeta(
        debugName: "append_local_message",
        argNames: ["fromUserId", "toUserId", "body", "timestamp"],
      );

  @override
  Future<String> crateApiDecryptMessageFromEnvelope(
      {required String envelope}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(envelope, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDecryptMessageFromEnvelopeConstMeta,
      argValues: [envelope],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDecryptMessageFromEnvelopeConstMeta =>
      const TaskConstMeta(
        debugName: "decrypt_message_from_envelope",
        argNames: ["envelope"],
      );

  @override
  Future<String> crateApiEncryptMessageForIdentity(
      {required String toIdentity, required String plaintext}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(toIdentity, serializer);
        sse_encode_String(plaintext, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiEncryptMessageForIdentityConstMeta,
      argValues: [toIdentity, plaintext],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEncryptMessageForIdentityConstMeta =>
      const TaskConstMeta(
        debugName: "encrypt_message_for_identity",
        argNames: ["toIdentity", "plaintext"],
      );

  @override
  Future<void> crateApiEndCall(
      {required PlatformInt64 userId, required String callId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(userId, serializer);
        sse_encode_String(callId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiEndCallConstMeta,
      argValues: [userId, callId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEndCallConstMeta => const TaskConstMeta(
        debugName: "end_call",
        argNames: ["userId", "callId"],
      );

  @override
  Future<String> crateApiGetAccountId() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetAccountIdConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetAccountIdConstMeta => const TaskConstMeta(
        debugName: "get_account_id",
        argNames: [],
      );

  @override
  Future<String> crateApiGetAccountPubkey() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetAccountPubkeyConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetAccountPubkeyConstMeta => const TaskConstMeta(
        debugName: "get_account_pubkey",
        argNames: [],
      );

  @override
  Future<CallState?> crateApiGetCurrentCallState() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_call_state,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetCurrentCallStateConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetCurrentCallStateConstMeta =>
      const TaskConstMeta(
        debugName: "get_current_call_state",
        argNames: [],
      );

  @override
  Future<String?> crateApiGetPubkeyTls(
      {required String host,
      required int port,
      required String caPem,
      required String passphrase,
      required String password,
      required PlatformInt64 userId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(host, serializer);
        sse_encode_u_16(port, serializer);
        sse_encode_String(caPem, serializer);
        sse_encode_String(passphrase, serializer);
        sse_encode_String(password, serializer);
        sse_encode_i_64(userId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetPubkeyTlsConstMeta,
      argValues: [host, port, caPem, passphrase, password, userId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetPubkeyTlsConstMeta => const TaskConstMeta(
        debugName: "get_pubkey_tls",
        argNames: ["host", "port", "caPem", "passphrase", "password", "userId"],
      );

  @override
  Future<String> crateApiListContactsJson() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiListContactsJsonConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiListContactsJsonConstMeta => const TaskConstMeta(
        debugName: "list_contacts_json",
        argNames: [],
      );

  @override
  Future<List<HistoryMessage>> crateApiLoadLocalHistory({BigInt? limit}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_opt_box_autoadd_usize(limit, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_history_message,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiLoadLocalHistoryConstMeta,
      argValues: [limit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoadLocalHistoryConstMeta => const TaskConstMeta(
        debugName: "load_local_history",
        argNames: ["limit"],
      );

  @override
  Future<HistoryBundle> crateApiLoginAndFetchHistoryTls(
      {required String host,
      required int port,
      required String caPem,
      required String passphrase,
      required String password,
      BigInt? limit}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(host, serializer);
        sse_encode_u_16(port, serializer);
        sse_encode_String(caPem, serializer);
        sse_encode_String(passphrase, serializer);
        sse_encode_String(password, serializer);
        sse_encode_opt_box_autoadd_usize(limit, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_history_bundle,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiLoginAndFetchHistoryTlsConstMeta,
      argValues: [host, port, caPem, passphrase, password, limit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoginAndFetchHistoryTlsConstMeta =>
      const TaskConstMeta(
        debugName: "login_and_fetch_history_tls",
        argNames: ["host", "port", "caPem", "passphrase", "password", "limit"],
      );

  @override
  Future<HistoryBundle> crateApiLoginAndLoadLocalHistoryTls(
      {required String host,
      required int port,
      required String caPem,
      required String passphrase,
      required String password,
      BigInt? limit}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(host, serializer);
        sse_encode_u_16(port, serializer);
        sse_encode_String(caPem, serializer);
        sse_encode_String(passphrase, serializer);
        sse_encode_String(password, serializer);
        sse_encode_opt_box_autoadd_usize(limit, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_history_bundle,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiLoginAndLoadLocalHistoryTlsConstMeta,
      argValues: [host, port, caPem, passphrase, password, limit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoginAndLoadLocalHistoryTlsConstMeta =>
      const TaskConstMeta(
        debugName: "login_and_load_local_history_tls",
        argNames: ["host", "port", "caPem", "passphrase", "password", "limit"],
      );

  @override
  Future<LoginResponse> crateApiLoginTls(
      {required String host,
      required int port,
      required String caPem,
      required String passphrase,
      required String password}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(host, serializer);
        sse_encode_u_16(port, serializer);
        sse_encode_String(caPem, serializer);
        sse_encode_String(passphrase, serializer);
        sse_encode_String(password, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_login_response,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiLoginTlsConstMeta,
      argValues: [host, port, caPem, passphrase, password],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoginTlsConstMeta => const TaskConstMeta(
        debugName: "login_tls",
        argNames: ["host", "port", "caPem", "passphrase", "password"],
      );

  @override
  Stream<String> crateApiOpenMessageStreamRegisterTls(
      {required String host,
      required int port,
      required String caPem,
      required String passphrase,
      required String password}) {
    final sink = RustStreamSink<String>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(host, serializer);
        sse_encode_u_16(port, serializer);
        sse_encode_String(caPem, serializer);
        sse_encode_String(passphrase, serializer);
        sse_encode_String(password, serializer);
        sse_encode_StreamSink_String_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiOpenMessageStreamRegisterTlsConstMeta,
      argValues: [host, port, caPem, passphrase, password, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiOpenMessageStreamRegisterTlsConstMeta =>
      const TaskConstMeta(
        debugName: "open_message_stream_register_tls",
        argNames: ["host", "port", "caPem", "passphrase", "password", "sink"],
      );

  @override
  Stream<String> crateApiOpenMessageStreamTls(
      {required String host,
      required int port,
      required String caPem,
      required String passphrase,
      required String password}) {
    final sink = RustStreamSink<String>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(host, serializer);
        sse_encode_u_16(port, serializer);
        sse_encode_String(caPem, serializer);
        sse_encode_String(passphrase, serializer);
        sse_encode_String(password, serializer);
        sse_encode_StreamSink_String_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiOpenMessageStreamTlsConstMeta,
      argValues: [host, port, caPem, passphrase, password, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiOpenMessageStreamTlsConstMeta =>
      const TaskConstMeta(
        debugName: "open_message_stream_tls",
        argNames: ["host", "port", "caPem", "passphrase", "password", "sink"],
      );

  @override
  Future<HistoryBundle> crateApiRegisterAndFetchHistoryTls(
      {required String host,
      required int port,
      required String caPem,
      required String passphrase,
      required String password,
      BigInt? limit}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(host, serializer);
        sse_encode_u_16(port, serializer);
        sse_encode_String(caPem, serializer);
        sse_encode_String(passphrase, serializer);
        sse_encode_String(password, serializer);
        sse_encode_opt_box_autoadd_usize(limit, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_history_bundle,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiRegisterAndFetchHistoryTlsConstMeta,
      argValues: [host, port, caPem, passphrase, password, limit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRegisterAndFetchHistoryTlsConstMeta =>
      const TaskConstMeta(
        debugName: "register_and_fetch_history_tls",
        argNames: ["host", "port", "caPem", "passphrase", "password", "limit"],
      );

  @override
  Future<HistoryBundle> crateApiRegisterAndLoadLocalHistoryTls(
      {required String host,
      required int port,
      required String caPem,
      required String passphrase,
      required String password,
      BigInt? limit}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(host, serializer);
        sse_encode_u_16(port, serializer);
        sse_encode_String(caPem, serializer);
        sse_encode_String(passphrase, serializer);
        sse_encode_String(password, serializer);
        sse_encode_opt_box_autoadd_usize(limit, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_history_bundle,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiRegisterAndLoadLocalHistoryTlsConstMeta,
      argValues: [host, port, caPem, passphrase, password, limit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRegisterAndLoadLocalHistoryTlsConstMeta =>
      const TaskConstMeta(
        debugName: "register_and_load_local_history_tls",
        argNames: ["host", "port", "caPem", "passphrase", "password", "limit"],
      );

  @override
  Future<LoginResponse> crateApiRegisterTls(
      {required String host,
      required int port,
      required String caPem,
      required String passphrase,
      required String password}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(host, serializer);
        sse_encode_u_16(port, serializer);
        sse_encode_String(caPem, serializer);
        sse_encode_String(passphrase, serializer);
        sse_encode_String(password, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_login_response,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiRegisterTlsConstMeta,
      argValues: [host, port, caPem, passphrase, password],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRegisterTlsConstMeta => const TaskConstMeta(
        debugName: "register_tls",
        argNames: ["host", "port", "caPem", "passphrase", "password"],
      );

  @override
  Future<void> crateApiRejectCall(
      {required PlatformInt64 userId,
      required String callId,
      required bool busy}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(userId, serializer);
        sse_encode_String(callId, serializer);
        sse_encode_bool(busy, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiRejectCallConstMeta,
      argValues: [userId, callId, busy],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRejectCallConstMeta => const TaskConstMeta(
        debugName: "reject_call",
        argNames: ["userId", "callId", "busy"],
      );

  @override
  Future<void> crateApiSendDirectMessageOverStream(
      {required PlatformInt64 userId,
      required PlatformInt64 toUserId,
      required String body}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(userId, serializer);
        sse_encode_i_64(toUserId, serializer);
        sse_encode_String(body, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSendDirectMessageOverStreamConstMeta,
      argValues: [userId, toUserId, body],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSendDirectMessageOverStreamConstMeta =>
      const TaskConstMeta(
        debugName: "send_direct_message_over_stream",
        argNames: ["userId", "toUserId", "body"],
      );

  @override
  Future<void> crateApiSendDirectMessageOverStreamToIdentity(
      {required PlatformInt64 userId,
      required String toIdentity,
      required String body}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(userId, serializer);
        sse_encode_String(toIdentity, serializer);
        sse_encode_String(body, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 24, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSendDirectMessageOverStreamToIdentityConstMeta,
      argValues: [userId, toIdentity, body],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSendDirectMessageOverStreamToIdentityConstMeta =>
      const TaskConstMeta(
        debugName: "send_direct_message_over_stream_to_identity",
        argNames: ["userId", "toIdentity", "body"],
      );

  @override
  Future<SendResult> crateApiSendDirectMessageTls(
      {required String host,
      required int port,
      required String caPem,
      required String passphrase,
      required String password,
      required PlatformInt64 toUserId,
      required String body}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(host, serializer);
        sse_encode_u_16(port, serializer);
        sse_encode_String(caPem, serializer);
        sse_encode_String(passphrase, serializer);
        sse_encode_String(password, serializer);
        sse_encode_i_64(toUserId, serializer);
        sse_encode_String(body, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 25, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_send_result,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSendDirectMessageTlsConstMeta,
      argValues: [host, port, caPem, passphrase, password, toUserId, body],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSendDirectMessageTlsConstMeta =>
      const TaskConstMeta(
        debugName: "send_direct_message_tls",
        argNames: [
          "host",
          "port",
          "caPem",
          "passphrase",
          "password",
          "toUserId",
          "body"
        ],
      );

  @override
  Future<void> crateApiSendMediaToIdentity(
      {required PlatformInt64 userId,
      required String toIdentity,
      required String mime,
      String? name,
      required List<int> bytes,
      BigInt? chunkSize}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(userId, serializer);
        sse_encode_String(toIdentity, serializer);
        sse_encode_String(mime, serializer);
        sse_encode_opt_String(name, serializer);
        sse_encode_list_prim_u_8_loose(bytes, serializer);
        sse_encode_opt_box_autoadd_usize(chunkSize, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 26, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSendMediaToIdentityConstMeta,
      argValues: [userId, toIdentity, mime, name, bytes, chunkSize],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSendMediaToIdentityConstMeta =>
      const TaskConstMeta(
        debugName: "send_media_to_identity",
        argNames: [
          "userId",
          "toIdentity",
          "mime",
          "name",
          "bytes",
          "chunkSize"
        ],
      );

  @override
  Future<void> crateApiSetContactNickname(
      {required String userId, String? nickname}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(userId, serializer);
        sse_encode_opt_String(nickname, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 27, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSetContactNicknameConstMeta,
      argValues: [userId, nickname],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSetContactNicknameConstMeta => const TaskConstMeta(
        debugName: "set_contact_nickname",
        argNames: ["userId", "nickname"],
      );

  @override
  Future<void> crateApiSetPubkeyOverStream(
      {required PlatformInt64 userId, required String pubkey}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(userId, serializer);
        sse_encode_String(pubkey, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 28, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSetPubkeyOverStreamConstMeta,
      argValues: [userId, pubkey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSetPubkeyOverStreamConstMeta =>
      const TaskConstMeta(
        debugName: "set_pubkey_over_stream",
        argNames: ["userId", "pubkey"],
      );

  @override
  Future<CallState> crateApiStartCall(
      {required PlatformInt64 userId,
      required PlatformInt64 remoteUserId,
      required bool enableVideo}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(userId, serializer);
        sse_encode_i_64(remoteUserId, serializer);
        sse_encode_bool(enableVideo, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 29, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_call_state,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiStartCallConstMeta,
      argValues: [userId, remoteUserId, enableVideo],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStartCallConstMeta => const TaskConstMeta(
        debugName: "start_call",
        argNames: ["userId", "remoteUserId", "enableVideo"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  CallState dco_decode_box_autoadd_call_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_call_state(raw);
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_usize(raw);
  }

  @protected
  CallDirection dco_decode_call_direction(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CallDirection.values[raw as int];
  }

  @protected
  CallState dco_decode_call_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return CallState(
      callId: dco_decode_String(arr[0]),
      remoteUserId: dco_decode_i_64(arr[1]),
      direction: dco_decode_call_direction(arr[2]),
      status: dco_decode_call_status(arr[3]),
      audioEnabled: dco_decode_bool(arr[4]),
      videoEnabled: dco_decode_bool(arr[5]),
    );
  }

  @protected
  CallStatus dco_decode_call_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CallStatus.values[raw as int];
  }

  @protected
  HistoryBundle dco_decode_history_bundle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return HistoryBundle(
      success: dco_decode_bool(arr[0]),
      message: dco_decode_String(arr[1]),
      userId: dco_decode_opt_box_autoadd_i_64(arr[2]),
      messages: dco_decode_list_history_message(arr[3]),
    );
  }

  @protected
  HistoryMessage dco_decode_history_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return HistoryMessage(
      id: dco_decode_i_64(arr[0]),
      fromUserId: dco_decode_i_64(arr[1]),
      toUserId: dco_decode_i_64(arr[2]),
      body: dco_decode_String(arr[3]),
      timestamp: dco_decode_String(arr[4]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<HistoryMessage> dco_decode_list_history_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_history_message).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  LoginResponse dco_decode_login_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return LoginResponse(
      success: dco_decode_bool(arr[0]),
      message: dco_decode_String(arr[1]),
      userId: dco_decode_opt_box_autoadd_i_64(arr[2]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  CallState? dco_decode_opt_box_autoadd_call_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_call_state(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_usize(raw);
  }

  @protected
  SendResult dco_decode_send_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SendResult(
      success: dco_decode_bool(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  CallState sse_decode_box_autoadd_call_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_call_state(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_usize(deserializer));
  }

  @protected
  CallDirection sse_decode_call_direction(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return CallDirection.values[inner];
  }

  @protected
  CallState sse_decode_call_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_callId = sse_decode_String(deserializer);
    var var_remoteUserId = sse_decode_i_64(deserializer);
    var var_direction = sse_decode_call_direction(deserializer);
    var var_status = sse_decode_call_status(deserializer);
    var var_audioEnabled = sse_decode_bool(deserializer);
    var var_videoEnabled = sse_decode_bool(deserializer);
    return CallState(
        callId: var_callId,
        remoteUserId: var_remoteUserId,
        direction: var_direction,
        status: var_status,
        audioEnabled: var_audioEnabled,
        videoEnabled: var_videoEnabled);
  }

  @protected
  CallStatus sse_decode_call_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return CallStatus.values[inner];
  }

  @protected
  HistoryBundle sse_decode_history_bundle(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_userId = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_messages = sse_decode_list_history_message(deserializer);
    return HistoryBundle(
        success: var_success,
        message: var_message,
        userId: var_userId,
        messages: var_messages);
  }

  @protected
  HistoryMessage sse_decode_history_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_fromUserId = sse_decode_i_64(deserializer);
    var var_toUserId = sse_decode_i_64(deserializer);
    var var_body = sse_decode_String(deserializer);
    var var_timestamp = sse_decode_String(deserializer);
    return HistoryMessage(
        id: var_id,
        fromUserId: var_fromUserId,
        toUserId: var_toUserId,
        body: var_body,
        timestamp: var_timestamp);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<HistoryMessage> sse_decode_list_history_message(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <HistoryMessage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_history_message(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  LoginResponse sse_decode_login_response(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_userId = sse_decode_opt_box_autoadd_i_64(deserializer);
    return LoginResponse(
        success: var_success, message: var_message, userId: var_userId);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  CallState? sse_decode_opt_box_autoadd_call_state(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_call_state(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_usize(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SendResult sse_decode_send_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_message = sse_decode_String(deserializer);
    return SendResult(success: var_success, message: var_message);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
      RustStreamSink<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_call_state(
      CallState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_call_state(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self, serializer);
  }

  @protected
  void sse_encode_call_direction(CallDirection self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_call_state(CallState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.callId, serializer);
    sse_encode_i_64(self.remoteUserId, serializer);
    sse_encode_call_direction(self.direction, serializer);
    sse_encode_call_status(self.status, serializer);
    sse_encode_bool(self.audioEnabled, serializer);
    sse_encode_bool(self.videoEnabled, serializer);
  }

  @protected
  void sse_encode_call_status(CallStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_history_bundle(HistoryBundle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_opt_box_autoadd_i_64(self.userId, serializer);
    sse_encode_list_history_message(self.messages, serializer);
  }

  @protected
  void sse_encode_history_message(
      HistoryMessage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_i_64(self.fromUserId, serializer);
    sse_encode_i_64(self.toUserId, serializer);
    sse_encode_String(self.body, serializer);
    sse_encode_String(self.timestamp, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_history_message(
      List<HistoryMessage> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_history_message(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_login_response(LoginResponse self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_opt_box_autoadd_i_64(self.userId, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_call_state(
      CallState? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_call_state(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_usize(
      BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_usize(self, serializer);
    }
  }

  @protected
  void sse_encode_send_result(SendResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}
